# Generated by Django 5.1.4 on 2025-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("talkw", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BadWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
